---
title: "User Manual"
author: "Updated October 12th, 2022"
subtitle: "`BayClump` v. 1.0.0"
date: "Table of Contents"
output:
  html_document: 
    toc: yes
    toc_float: true
    theme: cosmo
    fig_width: 5
    fig_height: 3
    fig_caption: yes
  pdf_document:
    toc: yes
    latex_engine: xelatex
urlcolor: blue
runtime: shiny
---

# `BayClump` Basics

`BayClump` version 0.9.2 was developed in `R` version 4.1.2 and `RStudio` version 1.4.1106. It has been tested up to `R` 4.2.1 and `RStudio` 2022.02.3+492. This app accompanies Román-Palacios et al. *under revision*: `BayClump`: Bayesian Calibration and Temperature Reconstructions for Clumped Isotope Thermometry. [Link](https://www.essoar.org/doi/abs/10.1002/essoar.10507995.2).

`BayClump` is separated into calibration and reconstruction workflows. Any calibration models selected on the Calibrations tab are automatically made available for use in the Reconstructions tab. At this time, only $Δ_{47}$-based calibrations and reconstructions are supported.

Please review the documentation presented under the user manual before using the app. We note that the code provided in the app is also available in an R package, `bayclumpr`.



